/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContenidoRouteImport } from './routes/contenido'
import { Route as LennaiRouteImport } from './routes/lennai'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ParaMamaRouteImport } from './routes/para-mama'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as RecuerdosRouteImport } from './routes/recuerdos'
import { Route as RutinasRouteImport } from './routes/rutinas'
import { Route as SeguimientoRouteImport } from './routes/seguimiento'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContenidoRoute = ContenidoRouteImport.update({
  id: '/contenido',
  path: '/contenido',
  getParentRoute: () => rootRouteImport,
} as any)
const LennaiRoute = LennaiRouteImport.update({
  id: '/lennai',
  path: '/lennai',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ParaMamaRoute = ParaMamaRouteImport.update({
  id: '/para-mama',
  path: '/para-mama',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuerdosRoute = RecuerdosRouteImport.update({
  id: '/recuerdos',
  path: '/recuerdos',
  getParentRoute: () => rootRouteImport,
} as any)
const RutinasRoute = RutinasRouteImport.update({
  id: '/rutinas',
  path: '/rutinas',
  getParentRoute: () => rootRouteImport,
} as any)
const SeguimientoRoute = SeguimientoRouteImport.update({
  id: '/seguimiento',
  path: '/seguimiento',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contenido': typeof ContenidoRoute
  '/lennai': typeof LennaiRoute
  '/onboarding': typeof OnboardingRoute
  '/para-mama': typeof ParaMamaRoute
  '/perfil': typeof PerfilRoute
  '/premium': typeof PremiumRoute
  '/recuerdos': typeof RecuerdosRoute
  '/rutinas': typeof RutinasRoute
  '/seguimiento': typeof SeguimientoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contenido': typeof ContenidoRoute
  '/lennai': typeof LennaiRoute
  '/onboarding': typeof OnboardingRoute
  '/para-mama': typeof ParaMamaRoute
  '/perfil': typeof PerfilRoute
  '/premium': typeof PremiumRoute
  '/recuerdos': typeof RecuerdosRoute
  '/rutinas': typeof RutinasRoute
  '/seguimiento': typeof SeguimientoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contenido': typeof ContenidoRoute
  '/lennai': typeof LennaiRoute
  '/onboarding': typeof OnboardingRoute
  '/para-mama': typeof ParaMamaRoute
  '/perfil': typeof PerfilRoute
  '/premium': typeof PremiumRoute
  '/recuerdos': typeof RecuerdosRoute
  '/rutinas': typeof RutinasRoute
  '/seguimiento': typeof SeguimientoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contenido'
    | '/lennai'
    | '/onboarding'
    | '/para-mama'
    | '/perfil'
    | '/premium'
    | '/recuerdos'
    | '/rutinas'
    | '/seguimiento'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contenido'
    | '/lennai'
    | '/onboarding'
    | '/para-mama'
    | '/perfil'
    | '/premium'
    | '/recuerdos'
    | '/rutinas'
    | '/seguimiento'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/contenido'
    | '/lennai'
    | '/onboarding'
    | '/para-mama'
    | '/perfil'
    | '/premium'
    | '/recuerdos'
    | '/rutinas'
    | '/seguimiento'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ContenidoRoute: typeof ContenidoRoute
  LennaiRoute: typeof LennaiRoute
  OnboardingRoute: typeof OnboardingRoute
  ParaMamaRoute: typeof ParaMamaRoute
  PerfilRoute: typeof PerfilRoute
  PremiumRoute: typeof PremiumRoute
  RecuerdosRoute: typeof RecuerdosRoute
  RutinasRoute: typeof RutinasRoute
  SeguimientoRoute: typeof SeguimientoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contenido': {
      id: '/contenido'
      path: '/contenido'
      fullPath: '/contenido'
      preLoaderRoute: typeof ContenidoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lennai': {
      id: '/lennai'
      path: '/lennai'
      fullPath: '/lennai'
      preLoaderRoute: typeof LennaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/para-mama': {
      id: '/para-mama'
      path: '/para-mama'
      fullPath: '/para-mama'
      preLoaderRoute: typeof ParaMamaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuerdos': {
      id: '/recuerdos'
      path: '/recuerdos'
      fullPath: '/recuerdos'
      preLoaderRoute: typeof RecuerdosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rutinas': {
      id: '/rutinas'
      path: '/rutinas'
      fullPath: '/rutinas'
      preLoaderRoute: typeof RutinasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seguimiento': {
      id: '/seguimiento'
      path: '/seguimiento'
      fullPath: '/seguimiento'
      preLoaderRoute: typeof SeguimientoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ContenidoRoute: ContenidoRoute,
  LennaiRoute: LennaiRoute,
  OnboardingRoute: OnboardingRoute,
  ParaMamaRoute: ParaMamaRoute,
  PerfilRoute: PerfilRoute,
  PremiumRoute: PremiumRoute,
  RecuerdosRoute: RecuerdosRoute,
  RutinasRoute: RutinasRoute,
  SeguimientoRoute: SeguimientoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
